Add missing get-status action implementation
This fixes commit 4aab95a9d6bdf4bdede51243fabf5e512ef7f797.

This implements the missing action get-status introduced since RAUC
v1.11[2].

[1]: https://rauc.readthedocs.io/en/latest/integration.html#custom-bootloader-backend-interface
[2]: https://github.com/rauc/rauc/commit/b872dcf7ffb0261d288b8d465c0863029dd484bd

diff --git a/bootloader-custom-backend b/bootloader-custom-backend
--- a/bootloader-custom-backend
+++ b/bootloader-custom-backend
@@ -454,6 +454,27 @@ set_primary() {
 	fi
 }
 
+# Output the bootname's slot of the partition number set by the bootloader in
+# the fdt using the RAUC system.conf file.
+get_current() {
+	local partition
+	local slot
+
+	if ! partition="$(fdtget /sys/firmware/fdt /chosen/bootloader partition)"
+	then
+		error "partition: Cannot get boot partition"
+		return 1
+	fi
+
+	if ! slot="$(get_slot "$partition")"
+	then
+		error "Cannot get booted slot"
+		return 1
+	fi
+
+	echo "$slot"
+}
+
 if [ "$1" = "get-state" ]
 then
 	shift
